### ISSUE TITLE
while_correction behavior

### ISSUE THREAD

**Issue by nkrusch** [seiller/pymwp#14]
We should discuss the behavior of this method:

https://github.com/seiller/pymwp/blob/4250ab22bab7d7057c4949712ca35b9e76b50fd5/pymwp/relation.py#L130-L136

This is the only place where `i` may be introduced. It is run on each while loop node during the analysis (after computing fixpoint).

Some open questions:

- What I don't get is that it seems that we are applying that correction to all the coef., and not only to the ones on the diagonal. What am I missing?

- I think that if the coefficient is not m (meaning it is either 0, w, p or i), then we need to change it to i: as of now, I don't think that's what we do.

- this expression is totally different if you change parentheses:

```
if mon.scalar == "p" or (mon.scalar == "w" and i == j)
```
 
to

```
if (mon.scalar == "p" or mon.scalar == "w") and i == j
```

the latter checks for diagonal scalars only.

**Comment by aubertc** [comment]
Remember, the original rules are 

![image](https://user-images.githubusercontent.com/16466689/120706326-ef09f100-c486-11eb-9ce1-cc8352ae27f6.png)


which seems to imply that "anything that isn't `m`" is problematic.

**Comment by nkrusch** [comment]
> "anything that isn't m" is problematic

Seems to me W says "diagonal all m" and "for all i,j cannot have p"?  

That would be "no p anywhere" which matches the expression in the code.

But can we not apply L is there is p somewhere? Or when we analyze `while` we must always use rule W?

**Comment by aubertc** [comment]
> 
> 
>     "anything that isn't m" is problematic
> 
> Seems to me W says "diagonal all m" and "for all i,j cannot have p"?

Sorry, I meant *on the diagonal*. You are correct that p can be problematic _anywhere_ (and so is `i`, but I guess we won't replace `i` with itself if it occurs somewhere) when applying W.

**Comment by seiller** [comment]
I think while loops should be analyses with W each time, and for loops can be analyzed with L. I think the implicit difference is that when entering a for we know from the start how many iterations we will do, so we can accept more behaviors than in a while.

**Comment by aubertc** [comment]
Briefly, the condition `if mon.scalar == "p" or (mon.scalar == "w" and i == j)` actually covers all the cases we need _for the W rule_:

- M^* is defined as 1 ⊕ M ⊕ M^2 ⊕ …, so there cannot be any `0` on the diagonal,
- The W rule says that a `p` _anywhere_ (including but not limited to the diagonal) is problematic,
- Hence, the only thing that remains to check on the diagonal only is the presence of `w`. 

(Taking into account the fact that replacing an `i` with an `i` is useless…)
