### ISSUE TITLE
Simplify sums

### ISSUE THREAD

**Issue by aubertc** [seiller/pymwp#16]
A small comment, but for instance

```
int main(){
    int y1, y2;
    y2 = y1 + y1;
}
```
gives

```
y2    |     +o  +o
y1    |     +o+w.delta(0,0)+p.delta(1,0)+w.delta(2,0)  +m
```

we could get rid of the `+o` in the lower-left corner.

**Comment by seiller** [comment]
That's exactly the thing I want to implement to simplify the evaluation, but it is haaaard! It may be NP-complete in fact.

**Comment by seiller** [comment]
Oh no sorry

**Comment by aubertc** [comment]
I was thinking about a more modest task of getting rid of the 0 :-)

**Comment by seiller** [comment]
I misread. Yes, we should get rid of all 0s; I do not know why we have them.
What I was talking about and want to implement is that w.delta(0,0)+w.delta(1,0)+w.delta(2,0) = w.

**Comment by seiller** [comment]
I think initially there was a "clean" method that was getting rid of zeroes.

**Comment by aubertc** [comment]
That's a small step in that direction (getting rid of the o), I would believe that the next one is to replace `w.delta(0,0)+m.delta(0,0)` with `m.delta(0,0)`, but I don't know if we can ever have that.

**Comment by seiller** [comment]
Non what you write is already taken care of by what we did with @ThomasRuby

**Comment by seiller** [comment]
And you want w.delta(0,0), not m.delta(0,0) as a result

**Comment by nkrusch** [comment]
> I think initially there was a "clean" method that was getting rid of zeroes.

[there was but it was handling specific edge cases only](https://depot.lipn.univ-paris13.fr/seiller/mwpanalysis/-/commit/8f308c3f56c36a5d1f0aa5d3873e7cc2ae7b97a9#note_3957) (not including this one). 

We would need to add a new version of clean to handle this kind of case.

**Comment by aubertc** [comment]
> And you want w.delta(0,0), not m.delta(0,0) as a result

Yes sorry. 

> No what you write is already taken care of by what we did with @ThomasRuby

I was not aware of that. I'll try to come up with an example to test / observe it.

In one of my test it went from

> +o+i.delta(1,0)+i.delta(1,0).delta(0,1)+i.delta(1,0).delta(1,1)+i.delta(1,0).delta(2,1)+w.delta(0,1)+p.delta(1,1)+w.delta(2,1)

to 

>  +o+i.delta(1,0)+w.delta(0,1)+p.delta(1,1)+w.delta(2,1)

which is quite nice, but I thought this was the only simplification implemented.

**Comment by seiller** [comment]
Oh, ok. But where are those 0's coming from? I would guess they are created by multiplications only. But then if we add some checks to not insert 0s it should be sufficient to get rid of them. And we should add something at the end of the multiplication that checks if the list is empty or not; if it's empty we add a 0 as sole element.

**Comment by ThomasRuby** [comment]
I think they come from here : https://github.com/seiller/pymwp/blob/master/pymwp/matrix.py#L147
In the fold (or reduce in python) of product. Maybe @nkrusch can confirm ?

**Comment by nkrusch** [comment]
That is one possible source, but in general the source of zero is anywhere where 0 is inserted into matrix e.g. creating an identity matrix will introduce 0s. In reduce, the role of zero is to represent the initial value of total, and by summing you get rid of zero (but I believe the source is not the reduce function in itself but the more underlying operations in that operation). 

In looking into this I discovered the following:

```python
ZERO = Polynomial([Monomial('o')])  # poly w/ zero monomial
poly_m = Polynomial([Monomial('m')])  # poly w/ m-monomial

print(ZERO + poly_m)  # +m   (only m remains)

# now add some deltas:
poly_m = Polynomial([Monomial('m', [(0, 0), (1, 1)])])

print(ZERO + poly_m)  # +o+m.delta(0,0).delta(1,1)
```

In adding polynomials we get rid of zero if there are no deltas, but not in the opposite case.

**Comment by nkrusch** [comment]
When adding two polynomials the following happens:

```python
        # iterate lists of monomials until the end of shorter list
        while j < poly_len:
            mono1, mono2 = new_list[i], polynomial.list[j]
            check = Polynomial.compare(mono1.deltas, mono2.deltas)

            # move to next when self (mono1) is smaller
            if check == Comparison.SMALLER:
                i = i + 1
```

In the example I had above about adding ZERO and polynomial with deltas,

1. comparing the two polynomials returns `o` is smaller (it has no deltas)
2. increment `i` to go to the next index (`o` remains in the result)
3. (later) append the remaining after `i`, so we get `+o+m.delta(0,0).delta(1,1)`

**Comment by seiller** [comment]
Ok. But then it can be easily solved following what I proposed earlier: remove all 0s encountered, and before returning the result produce a 0 if the list is empty.
This can be done both in the sum and the product.

**Comment by aubertc** [comment]
(side comment:

> I was not aware of that. I'll try to come up with an example to test / observe it.

I can confirm that it works, I went from `+w.delta(0,0)+m.delta(0,0)'` to `+m+w.delta(0,0)'` using the matrix fixpoint. No 0 were introduced, by the way.)

**Comment by nkrusch** [comment]
> remove all 0s encountered, and before returning the result produce a 0 if the list is empty

Let me implement a fix for this, for polynomial add and multiply.

**Comment by aubertc** [comment]
It's not a big deal, more of a reminder that some additional simplification can be done there.
