### ISSUE TITLE
Re-organize example folder

### ISSUE THREAD

**Issue by aubertc** [seiller/pymwp#21]
I've started to re-organize the example folder a bit with https://github.com/seiller/pymwp/commit/e261323f5f8d9d1ff50789881d2121810a5b8677 

A couple of observations:
- the "readme" at https://github.com/seiller/pymwp/blob/tests-examples/c_files/readme.md is very basics, we will have to expand it more "tutorial" style.
- It would be profitable to have "the usual examples" of non-polynomial programs (typically, exponential computation),
- I was a bit dumb and created this branch _before_ https://github.com/seiller/pymwp/pull/20 was created. As a result, some tests are not correct, but I suspect they have been fixed since.
- I have not changed the https://github.com/seiller/pymwp/tree/tests-examples/tests files, so I probably broke a couple of things.
- We need to discuss the fact that most / some of those programs cannot be compiled.

As of now,

- basics/declaration.c should give an identity matrix of dimension 1.
- basics/assign_value.c should give a matrix containing 0.
- basics/assign_variable.c should returns [m m // 0 0] (x / y).
- basics/if_else.c should returns [m m // m m](x / y) I believe.
- basics/if.c should returns [m m // 0 m](x / y) I believe.
- basics/while_1.c should returns something (not 100% sure what)
- not_infinite/exponent.c results in an empty matrix?

I have not checked the while_if.c, but I believe all the other examples are ok.

**Comment by aubertc** [comment]
After [merging with the simplification branch](https://github.com/seiller/pymwp/pull/23), there are still a couple of issues (but fewer!):

The most annoying one is that I had forgotten about the E2 rule, and I believe the implementation did too.
Let's discuss that in https://github.com/seiller/pymwp/issues/24, right now I will pretend that this issue does not exist.

> basics/declaration.c should give an identity matrix of dimension 1.

Right now, it returns `[[]]` instead of `[[m]]`

> basics/assign_value.c should give a matrix containing 0.

Right now, it returns `[[]]` instead of `[[o]]`

> basics/assign_variable.c should returns [m m // 0 0] (x / y).

fixed

> basics/if_else.c should returns [m m // m m](x / y) I believe.

fixed

> basics/if.c should returns [m m // 0 m](x / y) I believe.

fixed

> basics/while_1.c should returns something (not 100% sure what)

it now returns

```
y    |     +m  +o
x    |     +m  +m
```

which is correct.

>  It would be profitable to have "the usual examples" of non-polynomial programs (typically, exponential computation),
> not_infinite/exponent.c results in an empty matrix?

I had forgotten to add that file, and now added it in `c_files/infinite/exponent.c`. It seems to me that it is a valid implementation of exponentiation, _and yet I don't get infinite coefficients_.
What is wrong with it?

> I have not changed the https://github.com/seiller/pymwp/tree/tests-examples/tests files, so I probably broke a couple of things.

@nkrusch , If you give me an example of a commit adding one of those files to https://github.com/seiller/pymwp/tree/master/tests, I can carry on the other ones.

**Comment by aubertc** [comment]
With https://github.com/seiller/pymwp/commit/12b8da07007ef6a8069b544a258976d375fd351c I've added the examples from the original paper.

All of them, except the ones discussed below, are correct.

- Am I correct in reading in example3_1_c.c `+m+i.delta(1,0)+i.delta(2,0)` as "There is a choice for which no infinity appears"? If yes, then that example is good.
- I'm not sure what should be the outcome of example3_2.c. They re-use it in Example 3.5, but our analysis skips the X3 in the body of the loop.
- example3_4.c gives an error, probably because there I am mixing two operations in one statement.
- example5_1.c is empty, it is actually the same as https://github.com/seiller/pymwp/issues/10
- The bound for example7_11.c is absolutely horrible and I could not tell if we had the same as them. Is there a simpler way to check?
- I've skipped example 7.14, as it is more of a "meta-example" than an actual example.
- Similarly for 7.15.

**Comment by aubertc** [comment]
> >  It would be profitable to have "the usual examples" of non-polynomial programs (typically, exponential computation),
> > not_infinite/exponent.c results in an empty matrix?
> 
> I had forgotten to add that file, and now added it in c_files/infinite/exponent.c. It seems to me that it is a valid implementation of exponentiation, and yet I don't get infinite coefficients.
> What is wrong with it?

That is fixed with https://github.com/seiller/pymwp/commit/4b933c3b5a836e134c129b6b7a0759c6f785f61e : we do not support combined assignment operators yet.

**Comment by aubertc** [comment]
(And yes, we do get infinity coefficients in that example)

**Comment by nkrusch** [comment]
> @nkrusch , If you give me an example of a commit...

I saw this comment BTW but if we add a lot of tests it is probably a good idea to organize these tests better than how they are organized currently. I will get back to you.

**Comment by aubertc** [comment]
> example3_4.c gives an error, probably because there I am mixing two operations in one statement.

This is fixed with https://github.com/seiller/pymwp/commit/d9c0a735debedf97999f7641bcda6682ba1c93a2

**Comment by nkrusch** [comment]
OK that explains it. I will update demo. Currently I have to manually update examples then re-deploy the server. I'm looking into making this process more automated.

**Comment by aubertc** [comment]
I believe the server now serve the examples, that have been documented and clarified. Even if "always more" examples are possible, this issue can be closed as it does not contain outstanding issues.
