### ISSUE TITLE
Combining multiple choices when they lead to the same result

### ISSUE THREAD

**Issue by aubertc** [seiller/pymwp#33]
> What I was talking about and want to implement is that w.delta(0,0)+w.delta(1,0)+w.delta(2,0) = w.

_Originally posted by @seiller in https://github.com/seiller/pymwp/issues/16#issuecomment-854818910_

Just so you know: this can, indeed, happens.
https://github.com/seiller/pymwp/blob/master/c_files/infinite/exponent_2.c
gives

```
------------------------------------------------------------------------
result    |     +m+i.delta(0,0)+i.delta(1,0)+i.delta(2,0)  +o  +o
base    |     +i.delta(0,0)+i.delta(1,0)+i.delta(2,0)  +m  +o
i    |     +i.delta(0,0)+i.delta(1,0)+i.delta(2,0)  +o  +m
------------------------------------------------------------------------
```

There are two possible optimizations here, for instance looking at `+m+i.delta(0,0)+i.delta(1,0)+i.delta(2,0)`:
- Transform `i.delta(0,0)+i.delta(1,0)+i.delta(2,0)` into `i`
- Get rid of the `m` (but that should probably be automatic if we implement the first improvement).

**Comment by seiller** [comment]
In fact the transformation is already implemented in the delta_graphs branch (thanks to @ThomasRuby) for the case of i coefficients (i.e. in the delta_graph computed during the analysis). I think it would be too costly to implement it in the matrices though. Thomas will explain tomorrow but we now answer (without the matrix) the dense.c example within reasonable time.

**Comment by aubertc** [comment]
Excellent!

**Comment by aubertc** [comment]
This issue can be closed.
