### ISSUE TITLE
Braces mandatory around statements

### ISSUE THREAD

**Issue by aubertc** [seiller/pymwp#7]
Echoing https://github.com/seiller/pymwp/pull/6#issue-633723718 :

> I included the output matrix I get running the analysis on each. Also I found that not including curly braces around conditional statement throws an exception so I added curly braces. That should probably be a separate issue?

Yes, definitely. Apparently [pycparser](https://github.com/eliben/pycparser) should support it:

> pycparser very closely follows the C grammar provided in Annex A of the C99 standard (ISO/IEC 9899).

I briefly looked at [the specification](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf) and I believe statements without braces should be permitted.

**Comment by nkrusch** [comment]
Adding more details on this issue

Traceback
```
analysing If:
Traceback (most recent call last):
  File "pymwp/Analysis.py", line 353, in <module>
    rels, combinations = analysis()
  File "pymwp/Analysis.py", line 309, in analysis
    return compute_relation(name)
  File "pymwp/Analysis.py", line 323, in compute_relation
    index, rel_list = compute_rel(index, stmt)
  File "pymwp/Analysis.py", line 237, in compute_rel
    for child in node.iftrue.block_items:
AttributeError: 'Assignment' object has no attribute 'block_items'
```

source
https://github.com/seiller/pymwp/blob/71409e74aa0e1ff70ff38e457313af25e69d0901/pymwp/Analysis.py#L235-L240

The error happens because of the assumption `node.iftrue` has property `block_items` which it does not, if there are no curly braces, and it _does_ when C code has curly braces.

**Comment by aubertc** [comment]
Can we use something like

https://github.com/eliben/pycparser/blob/1706a39e0116dde0b2d1c52d67078a9a0ab4dbe7/pycparser/c_parser.py#L667-L672

? It seems to say "ok, if the code has the property `.Compound`, do this, otherwise do that (simpler thing).

**Comment by nkrusch** [comment]
I implemented a fix for this. It is not a very elegant fix; I will do it better in the analysis branch I am working on. In the meantime this fix will allow continuing work on the composition example without braces.
